fix: Add copy option if command is available

diff --git a/config/fzf-functions b/config/fzf-functions
--- a/config/fzf-functions
+++ b/config/fzf-functions
@@ -231,14 +231,26 @@ fenv () {
     printf "%s=%s\n" "$n" "${v//$'\n'}"
   done < <(env -0) > "$tmpfile"
 
+  local copy_command=()
+
+  if command -v pbcopy &> /dev/null; then
+    copy_command=(
+      --bind 'ctrl-y:execute-silent(printf \"%q\" {} | pbcopy)+abort'
+      --header 'Press CTRL-Y to copy command into clipboard'
+    )
+  elif command -v xsel &> /dev/null; then
+    copy_command=(
+      --bind 'ctrl-y:execute-silent(printf "%q" {} | xsel -ib)+abort'
+      --header 'Press CTRL-Y to copy command into clipboard'
+    )
+  fi
+
   cat -v "$tmpfile" |
     fzf-defaults \
-      --preview 'printf "%q" {}' --preview-window up:3:hidden:wrap \
-      --bind 'ctrl-/:toggle-preview' \
-      --bind 'ctrl-s:toggle-sort' \
-      --bind 'ctrl-y:execute-silent(printf "%q" {} | pbcopy)+abort' \
-      --color header:italic \
-      --header 'Press CTRL-Y to copy command into clipboard' |
+    --preview 'printf "%q" {}' --preview-window up:3:hidden:wrap \
+    --bind 'ctrl-/:toggle-preview' \
+    --color header:italic \
+    "${copy_command[@]}" |
     cut -d '=' -f "$(if [ "$showValue" = true ]; then echo "2-"; else echo "1"; fi)" |
     sed -E 's/^[[:space:]]*//' | sed -E 's/[[:space:]]*$//'
 }
@@ -280,11 +292,25 @@ fcmd () {
     type -f "$cm" 2>/dev/null || type "$cm" 2>/dev/null
   done > "$tmpfile"
 
+  local copy_command=()
+
+  if command -v pbcopy &> /dev/null; then
+    copy_command=(
+      --bind 'ctrl-y:execute-silent(echo -n {} | pbcopy)+abort'
+      --header 'Press CTRL-Y to copy command into clipboard'
+    )
+  elif command -v xsel &> /dev/null; then
+    copy_command=(
+      --bind 'ctrl-y:execute-silent(echo -n {} | xsel -ib)+abort'
+      --header 'Press CTRL-Y to copy command into clipboard'
+    )
+  fi
+
   echo "$available_commands" |
     fzf-defaults \
       --preview "
         rg -A 50 -B 1 -m 1 '^{} ' $tmpfile |
         bat -l bash --color=always -p -H 2" \
       --preview-window right:70% \
-      --bind 'ctrl-y:execute-silent(echo -n {} | pbcopy)+abort' || return 0
+      $copy_command || return 0
 }
