fix: Bug fixes for arrays and bindings in fzf

diff --git a/config/fzf-functions b/config/fzf-functions
--- a/config/fzf-functions
+++ b/config/fzf-functions
@@ -98,7 +98,7 @@ fed () {
   if [ -n "$2" ] && [ "$2" != "-" ]; then
     editor="$2"
   fi
-  $editor "$selection[@]"
+  $editor "${selection[@]}"
 }
 
 # Add files to stage area
@@ -195,7 +195,9 @@ fif () {
 # Group common used fzf configurations
 fzf-defaults () {
   fzf --height 50% --min-height 20 --border \
-    --bind "ctrl-/:change-preview-window(down|hidden|),alt-up:preview-page-up,alt-down:preview-page-down,ctrl-s:toggle-sort" \
+    --bind "ctrl-/:change-preview-window(down|hidden|)" \
+    --bind "alt-up:preview-page-up,alt-down:preview-page-down" \
+    --bind "ctrl-s:toggle-sort" \
     --header 'Press CTRL-/ to toggle preview' \
     "$@"
 }
@@ -236,12 +238,17 @@ fenv () {
 
   if command -v pbcopy &> /dev/null; then
     copy_command=(
-      --bind 'ctrl-y:execute-silent(printf \"%q\" {} | pbcopy)+abort'
+      --bind 'ctrl-y:execute-silent(printf "%q" {} | pbcopy)+abort'
       --header 'Press CTRL-Y to copy command into clipboard'
     )
   elif command -v xsel &> /dev/null; then
     copy_command=(
       --bind 'ctrl-y:execute-silent(printf "%q" {} | xsel -ib)+abort'
+      --header 'Press CTRL-Y to copy command into clipboard'
+    )
+  elif command -v pbcopy.exe &> /dev/null; then
+    copy_command=(
+      --bind 'ctrl-y:execute-silent(printf "%q" {} | pbcopy.exe)+abort'
       --header 'Press CTRL-Y to copy command into clipboard'
     )
   fi
@@ -305,6 +312,11 @@ fcmd () {
       --bind 'ctrl-y:execute-silent(echo -n {} | xsel -ib)+abort'
       --header 'Press CTRL-Y to copy command into clipboard'
     )
+  elif command -v pbcopy.exe &> /dev/null; then
+    copy_command=(
+      --bind 'ctrl-y:execute-silent(echo -n {} | pbcopy.exe)+abort'
+      --header 'Press CTRL-Y to copy command into clipboard'
+    )
   fi
 
   echo "$available_commands" |
@@ -313,5 +325,5 @@ fcmd () {
         rg -A 50 -B 1 -m 1 '^{} ' $tmpfile |
         bat -l bash --color=always -p -H 2" \
       --preview-window right:70% \
-      $copy_command || return 0
+      "${copy_command[@]}" || return 0
 }
